"""Rew1

Revision ID: 09a727169776
Revises: 53835a0f2b5b
Create Date: 2025-08-30 16:37:59.544036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a727169776'
down_revision: Union[str, Sequence[str], None] = '53835a0f2b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundle', sa.Column('is_standart', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundle', 'is_standart')
    # ### end Alembic commands ###
