"""empty message

Revision ID: ca3538b2433b
Revises: 40fabb13ae1e
Create Date: 2025-09-06 01:16:31.920989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3538b2433b'
down_revision: Union[str, Sequence[str], None] = '40fabb13ae1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modificator',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('uid_part', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['uid_part'], ['part.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('modificator_to_part',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_modificator', sa.UUID(), nullable=False),
    sa.Column('uid_part', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['uid_modificator'], ['modificator.uid'], ),
    sa.ForeignKeyConstraint(['uid_part'], ['part.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid_modificator', 'uid_part', name='_modificator_to_part')
    )
    op.drop_table('modificators')
    op.alter_column('bundle', 'is_standart',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('furniture', sa.Column('uid_order', sa.UUID(), nullable=True))
    op.add_column('furniture', sa.Column('uid_bundle', sa.UUID(), nullable=True))
    op.alter_column('furniture', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('furniture', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('furniture', 'photos_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'furniture', 'bundle', ['uid_bundle'], ['uid'])
    op.create_foreign_key(None, 'furniture', 'order', ['uid_order'], ['uid'])
    op.alter_column('part_preform', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('part_preform', 'part_uid',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('part_preform_part_uid_fkey'), 'part_preform', type_='foreignkey')
    op.create_foreign_key(None, 'part_preform', 'part', ['part_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'part_preform', type_='foreignkey')
    op.create_foreign_key(op.f('part_preform_part_uid_fkey'), 'part_preform', 'furniture', ['part_uid'], ['uid'])
    op.alter_column('part_preform', 'part_uid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('part_preform', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'furniture', type_='foreignkey')
    op.drop_constraint(None, 'furniture', type_='foreignkey')
    op.alter_column('furniture', 'photos_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('furniture', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('furniture', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('furniture', 'uid_bundle')
    op.drop_column('furniture', 'uid_order')
    op.alter_column('bundle', 'is_standart',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_table('modificators',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('uid_part', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uid_part'], ['part.uid'], name=op.f('modificators_uid_part_fkey')),
    sa.PrimaryKeyConstraint('uid', name=op.f('modificators_pkey'))
    )
    op.drop_table('modificator_to_part')
    op.drop_table('modificator')
    # ### end Alembic commands ###
