"""

Revision ID: 30d2ea1cc7bd
Revises: 5a9c85771f4b
Create Date: 2025-09-09 12:54:20.729682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d2ea1cc7bd'
down_revision: Union[str, Sequence[str], None] = '5a9c85771f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('client', sa.Column('last_name', sa.String(), nullable=False))
    op.alter_column('client', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('client', 'last_name')
    op.drop_column('client', 'first_name')
    # ### end Alembic commands ###
