"""Rew2

Revision ID: 40fabb13ae1e
Revises: 09a727169776
Create Date: 2025-08-30 17:22:29.785284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40fabb13ae1e'
down_revision: Union[str, Sequence[str], None] = '09a727169776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bundle', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bundle', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bundle', 'photos_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bundle', 'is_standart',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bundle', 'uid_order',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bundle', 'uid_order',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bundle', 'is_standart',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bundle', 'photos_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bundle', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bundle', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
