"""Initial revision

Revision ID: 53835a0f2b5b
Revises: a806a619c506
Create Date: 2025-08-30 16:24:03.153719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53835a0f2b5b'
down_revision: Union[str, Sequence[str], None] = 'a806a619c506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('furniture',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('photos_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('order',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('client_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_uid'], ['client.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('part',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_furniture', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uid_furniture'], ['furniture.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('part_preform',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('part_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['part_uid'], ['furniture.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('bundle',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('photos_link', sa.String(), nullable=False),
    sa.Column('uid_order', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uid_order'], ['order.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('material',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('uid_part', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uid_part'], ['part.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('modificators',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('uid_part', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uid_part'], ['part.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('furniture_to_bundle',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('uid_bundle', sa.UUID(), nullable=False),
    sa.Column('uid_furniture', sa.UUID(), nullable=False),
    sa.Column('furniture_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uid_bundle'], ['bundle.uid'], ),
    sa.ForeignKeyConstraint(['uid_furniture'], ['furniture.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid_bundle', 'uid_furniture', name='_furniture_to_bundle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('furniture_to_bundle')
    op.drop_table('modificators')
    op.drop_table('material')
    op.drop_table('bundle')
    op.drop_table('part_preform')
    op.drop_table('part')
    op.drop_table('order')
    op.drop_table('furniture')
    op.drop_table('client')
    # ### end Alembic commands ###
