ORDER = [
    {
        'id':'0',
        'Name':'Шкаф',
        'Description':'',
        'Parts': {
            'L1':{
                'count':2,
                'id':1,
                'Cost':1000,
                'Modificators':{
                    'M1':1,
                    'M2':22,
                    'M3':50
                }
            },
            'L2':{
                'count':1,
                'id':2,
                'Cost':3500,
                'Modificators':{
                    'M1':1,
                    'M2':22,
                    'M3':50
                }
            },
            'L3':{
                'count':1,
                'id':3,
                'Cost':6000,
                'Modificators':{
                    'M1':1,
                    'M2':22,
                    'M3':50
                }
            }
        }
    },
    {
        'id':'1',
        'Name':'Стол',
        'Description':'',
        'Parts': {
            '1':{
                'count':2,
                'id':1,
                'Cost':1000,
                'Modificators':{
                    'M1':1,
                    'M2':22,
                    'M3':50
                }
            },
            '2':{
                'count':1,
                'id':2,
                'Cost':3500,
                'Modificators':{
                    'M1':1,
                    'M2':22,
                    'M3':50
                }
            },
            '3':{
                'count':1,
                'id':3,
                'Cost':6000,
                'Modificators':{
                    'M1':1,
                    'M2':22,
                    'M3':50
                }
            }
        }
    }
]
