name: Flake8
on: [push]
jobs:
  Flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      # - name: Publish Image
      #   uses: matootie/github-docker@v3.1.0
      #   with:
      #     accessToken: ${{ github.token }} 
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          installer-parallel: true
      - name: Run QA
        run: |
          make QA
